---
- name: Create Security Group
  amazon.aws.ec2_security_group:
    name: "{{ sg_name }}"
    description: "{{ sg_description }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules: "{{ sg_rules }}"
  register: security_group

